spring.application.name=rbac-sringboot

spring.datasource.url=jdbc:postgresql://localhost:5432/test_springboot_rbac
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=user
spring.security.user.password=password

# Aplikasi JWT Config
app.jwtSecret=3cfa76ef14937c1c0ea519f8fc574a9f85b2bb04812f86a44138c31e342792b2
app.jwtExpirationMs=86400000